### ISSUE TITLE
cryptkeeper icon request

### ISSUE THREAD

**Issue by raknerak** [numixproject/numix-icon-theme-circle#2441]
ahmety@ahmeylnx:/usr/share/applications$ cat cryptkeeper.desktop 
[Desktop Entry]
Name=Cryptkeeper
Exec=cryptkeeper
Icon=cryptkeeper
Categories=System;GTK;Security
Terminal=false
Type=Application
StartupNotify=false

location of the icon theme /usr/share/pixmaps/cryptkeeper.png
![cryptkeeper](https://cloud.githubusercontent.com/assets/7880734/9028400/419dca74-3980-11e5-8915-7ba2b38ea063.png)

indictor theme shown as:

![selection_015](https://cloud.githubusercontent.com/assets/7880734/9028418/d859abea-3980-11e5-804a-6ae0499a7f2a.png)

**Comment by bil-elmoussaoui** [comment]
What's the location for the indicator icon? You should report the missing indicator icon here : [Numix Base](https://github.com/numixproject/numix-icon-theme)

**Comment by raknerak** [comment]
Actually, indicator icon is ok for me but the base icon can be circular. I could not find the indicator icon locatation it seems like for me as following in system tray..

![selection_016](https://cloud.githubusercontent.com/assets/7880734/9028451/d783f58a-3981-11e5-9107-cb4f8baad0a3.png)

**Comment by bil-elmoussaoui** [comment]
It's not the case ;) you can report that in [Harcode-Tray](https://github.com/bil-elmoussaoui/Hardcode-Tray) : a script that Numix uses to handle hardcoded Tray icons. Just one question, how you're having a Chromuim indicator icon? If you can give me more informations about that & the green indicator too ;)
Btw: you can fix spotify icon using the same script shared below ;)

**Comment by raknerak** [comment]
Actually, I probably did nothing on tray icons such as applying script. Probably, that is why I have those indicators :). Green indicator near wireless is (hangouts plugin of chrome) it starts with chromium browser. For the Chromium indicator, I actually just installed application and did nothing special .

I suppose I am doing something wrong to fix hardcode-tray: 

ahmety@ahmeylnx:/$ sudo -E python3 /usr/lib/python3/dist-packages/orca/scripts/apps/rhythmbox/script.py
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/orca/scripts/apps/rhythmbox/script.py", line 36, in <module>
    from .speech_generator import SpeechGenerator
SystemError: Parent module '' not loaded, cannot perform relative import
ahmety@ahmeylnx:/$ vi /usr/lib/python3/dist-packages/orca/scripts/apps/rhythmbox/script.py


Where is the script.py should I run?

**Comment by raknerak** [comment]
sorry I downloaded it and now I have following output:


ahmety@ahmeylnx:~/Downloads/Hardcode-Tray-master$ sudo -E python3 script.py 
Welcome to the tray icons hardcoder fixer! 

1 - Install 

2 - Reinstall 

Please choose: 1
Installing now..

spotify -- fixed using /usr/share/icons/Numix/22x22/status/spotify-indicator.svg
skype -- fixed using /usr/share/icons/Numix/22x22/status/skype-status-connecting-0.svg
skype -- fixed using /usr/share/icons/Numix/22x22/status/skype-status-connecting-1.svg
skype -- fixed using /usr/share/icons/Numix/22x22/status/skype-status-connecting-2.svg
skype -- fixed using /usr/share/icons/Numix/22x22/status/skype-status-connecting-3.svg
skype -- fixed using /usr/share/icons/Numix/22x22/status/skype-status-away.svg
skype -- fixed using /usr/share/icons/Numix/22x22/status/skype-status-away-notification.svg
skype -- fixed using /usr/share/icons/Numix/22x22/status/skype-status-connected.svg
skype -- fixed using /usr/share/icons/Numix/22x22/status/skype-status-connected-notification.svg
skype -- fixed using /usr/share/icons/Numix/22x22/status/skype-status-disturb.svg
skype -- fixed using /usr/share/icons/Numix/22x22/status/skype-status-disturb-notification.svg
skype -- fixed using /usr/share/icons/Numix/22x22/status/skype-status-invisible.svg
skype -- fixed using /usr/share/icons/Numix/22x22/status/skype-status-invisible-notification.svg
skype -- fixed using /usr/share/icons/Numix/22x22/status/skype-status-offline.svg
skype -- fixed using /usr/share/icons/Numix/22x22/status/skype-status-offline-notification.svg
fixing google-chrome failed with error:
	cp: cannot stat ‘/opt/google/chrome/chrome_100_percent.pak’: No such file or directory
	
	fs.js:432
	  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
	                 ^
	Error: ENOENT, no such file or directory 'chrome_100_percent_old.pak'
	    at Object.fs.openSync (fs.js:432:18)
	    at Object.fs.readFileSync (fs.js:286:15)
	    at unpack_proc (/home/ahmety/Downloads/Hardcode-Tray-master/database/scripts/node-chrome-pak.js:152:19)
	    at Object.<anonymous> (/home/ahmety/Downloads/Hardcode-Tray-master/database/scripts/node-chrome-pak.js:39:2)
	    at Module._compile (module.js:456:26)
	    at Object.Module._extensions..js (module.js:474:10)
	    at Module.load (module.js:356:32)
	    at Function.Module._load (module.js:312:12)
	    at Function.Module.runMain (module.js:497:10)
	    at startup (node.js:119:16)
	Traceback (most recent call last):
	  File "svg2png.py", line 11, in <module>
	    fout = open(symlfile, 'wb')
	FileNotFoundError: [Errno 2] No such file or directory: 'extracted/7360.png'
	
	fs.js:659
	  return binding.readdir(pathModule._makeLong(path));
	                 ^
	Error: ENOENT, no such file or directory './extracted'
	    at Object.fs.readdirSync (fs.js:659:18)
	    at pack_proc (/home/ahmety/Downloads/Hardcode-Tray-master/database/scripts/node-chrome-pak.js:105:21)
	    at Object.<anonymous> (/home/ahmety/Downloads/Hardcode-Tray-master/database/scripts/node-chrome-pak.js:37:2)
	    at Module._compile (module.js:456:26)
	    at Object.Module._extensions..js (module.js:474:10)
	    at Module.load (module.js:356:32)
	    at Function.Module._load (module.js:312:12)
	    at Function.Module.runMain (module.js:497:10)
	    at startup (node.js:119:16)
	    at node.js:902:3
	
fixing google-chrome failed with error:
	
	buffer.js:582
	    throw new RangeError('Trying to access beyond buffer length');
	          ^
	RangeError: Trying to access beyond buffer length
	    at checkOffset (buffer.js:582:11)
	    at Buffer.readUInt32LE (buffer.js:642:5)
	    at unpack_proc (/home/ahmety/Downloads/Hardcode-Tray-master/database/scripts/node-chrome-pak.js:156:27)
	    at Object.<anonymous> (/home/ahmety/Downloads/Hardcode-Tray-master/database/scripts/node-chrome-pak.js:39:2)
	    at Module._compile (module.js:456:26)
	    at Object.Module._extensions..js (module.js:474:10)
	    at Module.load (module.js:356:32)
	    at Function.Module._load (module.js:312:12)
	    at Function.Module.runMain (module.js:497:10)
	    at startup (node.js:119:16)
	Traceback (most recent call last):
	  File "svg2png.py", line 11, in <module>
	    fout = open(symlfile, 'wb')
	FileNotFoundError: [Errno 2] No such file or directory: 'extracted/7361.png'
	
	fs.js:659
	  return binding.readdir(pathModule._makeLong(path));
	                 ^
	Error: ENOENT, no such file or directory './extracted'
	    at Object.fs.readdirSync (fs.js:659:18)
	    at pack_proc (/home/ahmety/Downloads/Hardcode-Tray-master/database/scripts/node-chrome-pak.js:105:21)
	    at Object.<anonymous> (/home/ahmety/Downloads/Hardcode-Tray-master/database/scripts/node-chrome-pak.js:37:2)
	    at Module._compile (module.js:456:26)
	    at Object.Module._extensions..js (module.js:474:10)
	    at Module.load (module.js:356:32)
	    at Function.Module._load (module.js:312:12)
	    at Function.Module.runMain (module.js:497:10)
	    at startup (node.js:119:16)
	    at node.js:902:3
	
fixing google-chrome failed with error:
	
	buffer.js:582
	    throw new RangeError('Trying to access beyond buffer length');
	          ^
	RangeError: Trying to access beyond buffer length
	    at checkOffset (buffer.js:582:11)
	    at Buffer.readUInt32LE (buffer.js:642:5)
	    at unpack_proc (/home/ahmety/Downloads/Hardcode-Tray-master/database/scripts/node-chrome-pak.js:156:27)
	    at Object.<anonymous> (/home/ahmety/Downloads/Hardcode-Tray-master/database/scripts/node-chrome-pak.js:39:2)
	    at Module._compile (module.js:456:26)
	    at Object.Module._extensions..js (module.js:474:10)
	    at Module.load (module.js:356:32)
	    at Function.Module._load (module.js:312:12)
	    at Function.Module.runMain (module.js:497:10)
	    at startup (node.js:119:16)
	Traceback (most recent call last):
	  File "svg2png.py", line 11, in <module>
	    fout = open(symlfile, 'wb')
	FileNotFoundError: [Errno 2] No such file or directory: 'extracted/7358.png'
	
	fs.js:659
	  return binding.readdir(pathModule._makeLong(path));
	                 ^
	Error: ENOENT, no such file or directory './extracted'
	    at Object.fs.readdirSync (fs.js:659:18)
	    at pack_proc (/home/ahmety/Downloads/Hardcode-Tray-master/database/scripts/node-chrome-pak.js:105:21)
	    at Object.<anonymous> (/home/ahmety/Downloads/Hardcode-Tray-master/database/scripts/node-chrome-pak.js:37:2)
	    at Module._compile (module.js:456:26)
	    at Object.Module._extensions..js (module.js:474:10)
	    at Module.load (module.js:356:32)
	    at Function.Module._load (module.js:312:12)
	    at Function.Module.runMain (module.js:497:10)
	    at startup (node.js:119:16)
	    at node.js:902:3
	
fixing google-chrome failed with error:
	
	buffer.js:582
	    throw new RangeError('Trying to access beyond buffer length');
	          ^
	RangeError: Trying to access beyond buffer length
	    at checkOffset (buffer.js:582:11)
	    at Buffer.readUInt32LE (buffer.js:642:5)
	    at unpack_proc (/home/ahmety/Downloads/Hardcode-Tray-master/database/scripts/node-chrome-pak.js:156:27)
	    at Object.<anonymous> (/home/ahmety/Downloads/Hardcode-Tray-master/database/scripts/node-chrome-pak.js:39:2)
	    at Module._compile (module.js:456:26)
	    at Object.Module._extensions..js (module.js:474:10)
	    at Module.load (module.js:356:32)
	    at Function.Module._load (module.js:312:12)
	    at Function.Module.runMain (module.js:497:10)
	    at startup (node.js:119:16)
	Traceback (most recent call last):
	  File "svg2png.py", line 11, in <module>
	    fout = open(symlfile, 'wb')
	FileNotFoundError: [Errno 2] No such file or directory: 'extracted/7359.png'
	
	fs.js:659
	  return binding.readdir(pathModule._makeLong(path));
	                 ^
	Error: ENOENT, no such file or directory './extracted'
	    at Object.fs.readdirSync (fs.js:659:18)
	    at pack_proc (/home/ahmety/Downloads/Hardcode-Tray-master/database/scripts/node-chrome-pak.js:105:21)
	    at Object.<anonymous> (/home/ahmety/Downloads/Hardcode-Tray-master/database/scripts/node-chrome-pak.js:37:2)
	    at Module._compile (module.js:456:26)
	    at Object.Module._extensions..js (module.js:474:10)
	    at Module.load (module.js:356:32)
	    at Function.Module._load (module.js:312:12)
	    at Function.Module.runMain (module.js:497:10)
	    at startup (node.js:119:16)
	    at node.js:902:3
	

Done , Thank you for using the Hardcode-Tray fixer!

**Comment by raknerak** [comment]
Here is the latest status of the indicators. I can not still solve chromium and hangouts indicator issue.

![selection_016](https://cloud.githubusercontent.com/assets/7880734/9028711/757af574-398a-11e5-8f09-2c6838fb43fa.png)

**Comment by bil-elmoussaoui** [comment]
As i said before, open a new issue in Hardcode-Tray as this is not right place to fix them ;)

**Comment by raknerak** [comment]
Ok, I will do it for chromium but I also tried chrome version which is being downloaded on chrome website. (not chromium) your script does not return error but browser theme was broken after the script.

**Comment by raknerak** [comment]
I did your beta Hardcode-Tray to fix following issue regarding google-Chrome: 

https://github.com/bil-elmoussaoui/Hardcode-Tray/issues/75

But it does not fix the issue. 

Please be informed.

**Comment by bil-elmoussaoui** [comment]
This not a Numix issue.

**Comment by raknerak** [comment]
I tried beta version of Hardcode-Tray with changing extracted folder,

I found following error:

(b'', b'') (b'', b"\nmodule.js:340\n    throw err;\n          ^\nError: Cannot find module '/home/ahmety/Downloads/Hardcode-Tray-beta/database/scripts/node-chrome-pak.js '\n    at Function.Module._resolveFilename (module.js:338:15)\n    at Function.Module._load (module.js:280:25)\n    at Function.Module.runMain (module.js:497:10)\n    at startup (node.js:119:16)\n    at node.js:902:3\n")
fixing google-chrome failed with error:
	
	buffer.js:582
	    throw new RangeError('Trying to access beyond buffer length');
	          ^
	RangeError: Trying to access beyond buffer length
	    at checkOffset (buffer.js:582:11)
	    at Buffer.readUInt32LE (buffer.js:642:5)
	    at unpack_proc (/home/ahmety/Downloads/Hardcode-Tray-beta/database/scripts/node-chrome-pak.js:156:27)
	    at Object.<anonymous> (/home/ahmety/Downloads/Hardcode-Tray-beta/database/scripts/node-chrome-pak.js:39:2)
	    at Module._compile (module.js:456:26)
	    at Object.Module._extensions..js (module.js:474:10)
	    at Module.load (module.js:356:32)
	    at Function.Module._load (module.js:312:12)
	    at Function.Module.runMain (module.js:497:10)
	    at startup (node.js:119:16)

**Comment by bil-elmoussaoui** [comment]
@Foggalong Ok, it's not a hardcoded indicator. It took me sometime to figure this out, the application is using this icon `gtk-dialog-authentication-panel` and we already have it in Numix Base
